services:
  - type: web
    name: pdf-processor
    runtime: docker
    dockerfile: Dockerfile
    envVars:
      - key: REDIS_URL
        fromDatabase:
          name: pdf-redis
          property: connectionString
      - key: MAX_PAGES
        value: "50"
      - key: SECRET_KEY
        generateValue: true
    plan: free
    numInstances: 1

  - type: redis
    name: pdf-redis
    plan: free