services:
  - type: web
    name: pdf-processor
    runtime: docker
    dockerfile: Dockerfile
    buildCommand: |
      apt-get update && apt-get install -y libjpeg-dev zlib1g-dev libfreetype6-dev libharfbuzz-dev libfribidi-dev liblcms2-dev
      pip install --upgrade pip
      pip install -r requirements.txt
    envVars:
      - key: REDIS_URL
        fromDatabase:
          name: pdf-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: MAX_PAGES
        value: "50"
      - key: PORT
        value: "10000"
    plan: free
    buildCaching: true
    buildTimeout: 3600
    autoDeploy: true

  - type: redis
    name: pdf-redis
    plan: free
    region: oregon
